# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

# Starts the ODS/API in SharedInstance mode without Admin App

version: '3.8'

services:
  db-ods:
    image: edfialliance/ods-api-db-ods:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5402:5432"
    volumes:
      -  vol-db-ods:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods

  db-admin:
    image: edfialliance/ods-api-db-admin:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5401:5432"
    volumes:
      -  vol-db-admin:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-admin

  api:
    image: edfialliance/ods-api-web-api:${TAG}
    ports:
       - "5000:80"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ODS_DB: db-ods
      ADMIN_DB: db-admin
      API_MODE: "SharedInstance"
    volumes:
      - ${LOGS_FOLDER}:/app/logs
    depends_on:
       - db-ods
       - db-admin
    restart: always
    hostname: api
    container_name: ed-fi-ods-api

volumes:
  vol-db-admin:
    driver: local
    name: vol-db-admin
  vol-db-ods:
    driver: local
    name: vol-db-ods
