# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: "3.8"

services:
  db-admin:
    image: "${ADMIN_DB_IMAGE:-edfialliance/ods-api-db-admin:${TAG}}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      ODS_PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      CONTEXT_KEY: "schoolYearFromRoute"
      API_MODE: "${ADMIN_API_MODE}"
    volumes:
      - vol-db-admin:/var/lib/postgresql/data
      - ./bootstrap.sh:/docker-entrypoint-initdb.d/2-bootstrap.sh
    restart: always
    container_name: ed-fi-db-admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  nginx:
    image: edfialliance/ods-api-web-gateway:${GATEWAY_TAG}
    environment:
      ODS_VIRTUAL_NAME: "${ODS_VIRTUAL_NAME:-api}"
      ADMIN_API_VIRTUAL_NAME: "${ADMIN_API_VIRTUAL_NAME:-adminapi}"
    ports:
      - "443:443"
    container_name: ed-fi-gateway
    restart: always
    hostname: nginx
    volumes:
      - ../../../ssl:/ssl/
    depends_on:
      - api
      - adminapi

  api:
    image: edfialliance/ods-api-web-api:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      ADMIN_POSTGRES_HOST: pb-admin
      PATH_BASE: "${ODS_VIRTUAL_NAME:-api}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
      ODS_WAIT_POSTGRES_HOSTS: "pb_ods_2022 pb_ods_2023 "
      API_HEALTHCHECK_TEST: ${API_HEALTHCHECK_TEST?Please consult env.example to set the API healthcheck test}
      NPG_POOLING_ENABLED: "${NPG_POOLING_ENABLED:-false}"
      NPG_API_MAX_POOL_SIZE_ODS: "${NPG_API_MAX_POOL_SIZE_ODS}"
      NPG_API_MAX_POOL_SIZE_ADMIN: "${NPG_API_MAX_POOL_SIZE_ADMIN}"
      NPG_API_MAX_POOL_SIZE_SECURITY: "${NPG_API_MAX_POOL_SIZE_SECURITY}"
      NPG_API_MAX_POOL_SIZE_MASTER: "${NPG_API_MAX_POOL_SIZE_MASTER}"
      ODS_CONNECTION_STRING_ENCRYPTION_KEY: "${ODS_CONNECTION_STRING_ENCRYPTION_KEY}"
      ASPNETCORE_ENVIRONMENT: "docker"
    volumes:
      - ${LOGS_FOLDER}:/app/logs
      - ./appsettings.Docker.json:/app/appsettings.docker.json
    depends_on:
      - pb-admin
      - pb_ods_2022
      - pb_ods_2023
    restart: always
    hostname: api
    container_name: ed-fi-ods-api
    healthcheck:
      test: $$API_HEALTHCHECK_TEST
      start_period: "60s"
      retries: 3

  adminapi:
    image: edfialliance/ods-admin-api:${ADMINAPI_TAG}
    environment:
      ADMIN_POSTGRES_HOST: pb-admin
      POSTGRES_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASEENGINE: "PostgreSql"      
      AUTHORITY: ${AUTHORITY}
      ISSUER_URL: ${ISSUER_URL}
      SIGNING_KEY: ${SIGNING_KEY}
      ADMIN_API_VIRTUAL_NAME: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
      API_INTERNAL_URL: ${API_INTERNAL_URL}
      AppSettings__DefaultPageSizeOffset: ${PAGING_OFFSET:-0}
      AppSettings__DefaultPageSizeLimit: ${PAGING_LIMIT:-25}
      Authentication__AllowRegistration: "true"
      SwaggerSettings__EnableSwagger: "true"
    depends_on:
      - pb-admin
    restart: always
    hostname: ${ADMIN_API_VIRTUAL_NAME:-adminapi}
    container_name: ed-fi-adminapi
    healthcheck:
      test: ${ADMIN_API_HEALTHCHECK_TEST}
      start_period: "60s"
      retries: 3

  db-ods-2022:
    image: edfialliance/ods-api-db-ods-minimal:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    volumes:
      - vol-db-ods-2022:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods-2022
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  pb_ods_2022:
    image: bitnami/pgbouncer:1.23.4
    environment:
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      PGBOUNCER_EXTRA_FLAGS: ${PGBOUNCER_EXTRA_FLAGS}
      POSTGRESQL_USER: "${POSTGRES_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_HOST: db-ods-2022
      PGBOUNCER_SET_DATABASE_USER: "yes"
      PGBOUNCER_SET_DATABASE_PASSWORD: "yes"
    restart: always
    container_name: ed-fi-pb-ods-2022
    depends_on:
      - db-ods-2022
  
  db-ods-2023:
    image: edfialliance/ods-api-db-ods-minimal:${TAG}
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TPDM_ENABLED: "${TPDM_ENABLED:-true}"
    volumes:
      - vol-db-ods-2023:/var/lib/postgresql/data
    restart: always
    container_name: ed-fi-db-ods-2023
    healthcheck:
      test: ["CMD-SHELL", "pg_isready  -U ${POSTGRES_USER}"]
      start_period: "60s"
      retries: 3

  pb_ods_2023:
    image: bitnami/pgbouncer:1.23.4
    environment:
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      PGBOUNCER_EXTRA_FLAGS: ${PGBOUNCER_EXTRA_FLAGS}
      POSTGRESQL_USER: "${POSTGRES_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_HOST: db-ods-2023
      PGBOUNCER_SET_DATABASE_USER: "yes"
      PGBOUNCER_SET_DATABASE_PASSWORD: "yes"
    restart: always
    container_name: ed-fi-pb-ods-2023
    depends_on:
      - db-ods-2023
  
  pb-admin:
    image: bitnami/pgbouncer:1.23.4
    environment:
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_PORT: "${PGBOUNCER_LISTEN_PORT:-6432}"
      PGBOUNCER_EXTRA_FLAGS: ${PGBOUNCER_EXTRA_FLAGS}
      POSTGRESQL_USER: "${POSTGRES_USER}"
      POSTGRESQL_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_HOST: db-admin
      PGBOUNCER_SET_DATABASE_USER: "yes"
      PGBOUNCER_SET_DATABASE_PASSWORD: "yes"
    restart: always
    container_name: ed-fi-pb-admin
    depends_on:
      - db-admin

volumes:
  vol-db-admin:
    driver: local
    name: vol-db-admin
  vol-db-ods-2022:
    driver: local
    name: vol-db-ods-2022
  vol-db-ods-2023:
    driver: local
    name: vol-db-ods-2023
