name: Deploy ods-api-web-gateway-sandbox image

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

permissions: read-all

env:
  ENABLE_PRE_IMAGE: ${{ !startsWith(github.ref, 'refs/tags/v') }}

jobs:
  build:
    name: Deploy ods-api-web-gateway-sandbox image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ed-Fi-ODS-Docker
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: edfialliance/ods-api-web-gateway-sandbox
          labels: |
            org.opencontainers.image.title=ods-api-web-gateway-sandbox
            org.opencontainers.image.description=Docker Image for the NGINX Gateway for Sandbox
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{raw}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=raw,value=pre,enable=${{ env.ENABLE_PRE_IMAGE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6.11.0
        with:
          context: Web-Gateway-Sandbox/Alpine
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
