name: Deploy ods-api-db-sandbox image

on:
  push:
    branches: [main, ODS-*]
  release:
  workflow_dispatch:

jobs:
  build:
    name: Deploy ods-api-db-sandbox image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ed-Fi-ODS-Docker
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER__PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: edfialliance/ods-api-db-sandbox
          tags: |
            type=semver,pattern={{version}},event=tag
            type=semver,pattern={{major}}.{{minor}},event=tag
            type=semver,pattern={{major}},event=tag
            type=raw,value=pre,branch=$repo.default_branch

      - name: Check Labels and Tags
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
