name: Deploy ods-api-web-sandbox-admin image

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  ENABLE_PRE_IMAGE: ${{ !startsWith(github.ref, 'refs/tags/v') }}

jobs:
  build:
    name: Deploy ods-api-web-sandbox-admin image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ed-Fi-ODS-Docker
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER__PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: edfialliance/ods-api-web-sandbox-admin
          labels: |
            org.opencontainers.image.title=ods-api-web-sandbox-admin
            org.opencontainers.image.description=Docker Image for the Sandbox Admin for PostgreSQL
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{raw}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=raw,value=pre,enable=${{ env.ENABLE_PRE_IMAGE }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: Web-Sandbox-Admin/Alpine/pgsql
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
