name: Lint and Build Docker Files

on:
  push:
    branches: [main-6x]
  pull_request:
    branches: [main, 'ODS-*']
  workflow_dispatch:

jobs:
  build:
    name: Lint and Build Docker Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Ed-Fi-ODS-Docker
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      # https://github.com/github/super-linter#how-to-use
      - name: Lint Docker Files
        uses: github/super-linter@431ee7836e8cdce5a460b0db682d9169563d919b # v4.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_DOCKERFILE_HADOLINT: true

      - name: Build the Docker images
        shell: pwsh
        run: |
          dir -recurse -file -include Docker* | select Directory |
          ForEach-Object {
            docker build $_.Directory
          }
